### ISSUE TITLE
register / unregister: read email from config

### ISSUE THREAD

**Issue by petersutter** [gardener/gardenctl#124]
Currently, `gardenctl` either accepts the email(s) as part of the `register`/`unregister` command or reads a github url from the config and tries to guess the email by taking the `USER` env var and calling [github's users](https://developer.github.com/v3/users/#get-a-single-user) endpoint. This only works for SAP's landscapes.

Why is this done via github api?
Why not add a new config property for setting the email address on `top` level and optionally on `gardenClusters` level to override the global email setting?

```yaml
email: my-operator-mail@example.com
gardenClusters:
- name: dev
  kubeConfig: ~/clusters/dev/kubeconfig.yaml
- name: prod
  kubeConfig: ~/clusters/prod/kubeconfig.yaml
  email: my-other-operator-mail@example.com
```
