### ISSUE TITLE
`garden target project`: expected syntax

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardenctl#16]
The namespaces in the Garden clusters which are used as projects have the following labels:

```yaml
metadata:
  name: garden-my-project
  labels:
    garden.sapcloud.io/role: project
    project.garden.sapcloud.io/name: my-project
```

The `gardenctl target project` command expects to enter the name of the namespace, not the name of the project (`gardenctl target project garden-my-project` instead of `gardenctl target project my-project`).

Can we change that?
