### ISSUE TITLE
Improve handling of external resources

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardenctl#192]
**What would you like to be added**:
From time to time `gardenctl` is leaking cloud provider resources which is hard to find out and delete later.
An example is `gardenctl ssh <node-name>` which is ensuring the required node is accessible via pubic internet by creating a public IP, and depending on the cloud provider creates a bastion machine. If the ssh session is not gracefully deleted - the cloud resources are leaked and the end users might not be able to purge them manually. 

To prevent resource leaking, a CRD can be used to track these resources and a controller that is taking care to manage them, including to delete them properly. Something very similar and already implemented is the [terminal-controller](https://github.com/gardener/terminal-controller-manager). 

**Why is this needed**:
Prevent cloud resource leaking.

**Comment by tedteng** [comment]
I will take a look ,  you can assign it to me

**Comment by tedteng** [comment]
after investigation there are the following scenarios will cause the leaking and other issues. 

* scenarios 1) status checks timeout https://github.com/gardener/gardenctl/issues/191
Event instance status is running, till need to wait the status check passed before ec2 instance able to access.  some of case status check may take more than 60s 

Error
```
Waiting 60 seconds until ports are open.
Warning: Permanently added '<some-public-ip>' (ECDSA) to the list of known hosts.
channel 0: open failed: connect failed: Connection timed out
stdio forwarding failed
kex_exchange_identification: Connection closed by remote host
exit status 255
```

* scenarios 2) status checks not passed or other issues maybe leads the issues too.  
* scenarios 3) User A , B  access cluster for troubleshooting.
User A access creates `bastion ec2 A`, SG-bastion which includes rules host(22) and bastion(22) after executed `gardenctl ssh xxxx`.  graceful exit deletes everything normally.  but User B online this time. 

User A exit normally, `bastion ec2 A` , SG-bastion rule host(22)/bastion(22) has been deleted, `bastion ec2 B`  exist caused the dependent object can't delete SG-bastion
Error
```
  (3/3) Clean up bastion host secursity group

  Waiting 45 seconds until instance is deleted to remove all dependencies.

An error occurred (DependencyViolation) when calling the DeleteSecurityGroup operation: resource sg-032dfba7cf9b03b7a has a dependent object
exit status 2
````

there are two options that lead to two issues. 
* option 1
User B session hung can't type anything in terminal/iTerm due to SG rules delete when User A exit.  waiting session timeout then calls `cleanupAwsBastionHost` by defer. because SG-bastion rule already deleted by User A, SG-bastion not delete and still exists.
Error
````
  (2/3) Close SSH Port on Node.

An error occurred (InvalidPermission.NotFound) when calling the RevokeSecurityGroupIngress operation: The specified rule does not exist in this security group.
```

opinion 2 
User B session hung can't type anything, then close the terminal/iTerm windows. `bastion ec2 B` and SG-bastion remaining in the cluster and occupy more t2 resources. 

as a result, the root cause is https://github.com/gardener/gardenctl/blob/755ffa48dbc728f0d83ce41a3a0eee780a3ce6d4/pkg/cmd/ssh_aws.go#L212 the instance check does not work which create and occupy multiple `bastion ec2` instances resource in some cases to leads delete flow blocked.

**Comment by tedteng** [comment]
Signed-off
PR: https://github.com/gardener/gardenctl/pull/195

**Comment by vpnachev** [comment]
@hardikdr @prashanth26 as MCM maintainers could you provide your feedback about whether it is possible to manage SSH access to the VMs via the `machine.sapcloud.io/v1alpha1.Machine` resource. On some providers only a public IP has to be attached, on others a bastion VM has to be deployed and bridged with the private network of the shoot.

**Comment by petersutter** [comment]
@vpnachev I really like the idea of using the `machine.sapcloud.io/v1alpha1.Machine` resource to manage SSH access to the VMs or maybe even have a dedicated CRD with an own controller that manages this and just makes use of `machine.sapcloud.io/v1alpha1.Machine` in case a machine is needed.

Once we have this in place we could even use the terminal-controller-manager for having ssh access from the webterminal.

**Comment by tedteng** [comment]
ok. I will create ssh-controller-manager CRD in the seed to create/manage the VMs

**Comment by hardikdr** [comment]
I overall agree with @vpnachev @petersutter.

A minor variant to what is proposed could be, we simply create a dedicated `bastion` MachineDeployment with PubilcIPs enabled[via classes]. So in case machine-creation fails, it could be automated by deployment-controller.
- Though currently, MCM assumes that the created machines are going to k8s nodes, and if they don't health-check replaces them. We might want to have a `disable-health-check` flag at MCM to avoid this, pls create an issue if you see a need.
 
We might also want to think, where such bastion-machine CRDs should be created?
- If at seed's apiserver, existing MCM can take care of it. 
- If at shoot's apiserver, we might want to deploy on-demand MCM there, the one running in seed can't read the CRDs at the shoot. This could also empower users to have properly configured bastions available on their own.  
 
Either way, machine-crds could be used to support the bastions.

**Comment by tedteng** [comment]
correct me if I in the wrong approach. 

as far as I can think now,  the existing MCM manages to create/remove lifecycle for all bastion resources, VM, security group for VM, and Public IPs, all in the customer subscriptions. 

If I code and implement `bastion-machine CRDs` in seed, the `bastion-machine CRDs`  will call MCM to manage the bastion VM cross all cloud providers(aws,az,gcp...). however, need to have `disable-health-check flag`  as a new request in MCM

Please me know if there any concerns which I  am not cover for the ssh bastion lifecycle.

**Comment by petersutter** [comment]
> I overall agree with @vpnachev @petersutter.
> 
> A minor variant to what is proposed could be, we simply create a dedicated `bastion` MachineDeployment with PubilcIPs enabled[via classes]. So in case machine-creation fails, it could be re-created automatically by deployment-controller.

👍 

> * Though currently, MCM assumes that the created machines are going to k8s nodes, and if they don't health-check replaces them. We might want to have a `disable-health-check` flag at MCM to avoid this, pls create an issue if you see a need.

👍 

> We might also want to think, where such bastion-machine CRDs should be created?
> 
> * If at seed's apiserver, existing MCM can take care of it.
> * If at shoot's apiserver, we might want to deploy on-demand MCM there, the one running in seed can't read the CRDs at the shoot. This could also empower users to have properly configured bastions available on their own.

hm, I don't have a strong opinion on that. Anyone else?

What we should also keep in mind is that the seeds and shoots could be in isolated environments (e.g. not accessible from the internet), hence the `ssh-controller-manager` or however you want to call it should run on each seed, similar to the `gardenlet` approach.

**Comment by petersutter** [comment]
@tedteng before you start with the implementation, can you please share an example of such a `bastion-machine` CR?
And also share an example of the `MachineDeployment` CR that you would create when acting upon the `bastion-machine` CR.

**Comment by tedteng** [comment]
> @tedteng before you start with the implementation, can you please share an example of such a `bastion-machine` CR?
> And also share an example of the `MachineDeployment` CR that you would create when acting upon the `bastion-machine` CR.

sure I am trying to figure out the whole approach first make sure it is correct approach . 

correct me if it is not correct for the following CR, I new for MCM , few questions 

- `t2.nano` as the smallest instance not in AWSMachineClass yet
- I haven't get the idea about Public IPs yet. 
- about exist host node, does MCM available to update `securityGroups` to open 22 port


`bastion-machine`
```
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Worker
metadata:
  name: bar-bastion 
  namespace: shoot--foo--bar
spec:
  type: aws
  region: eu-west-1
  secretRef:
    name: cloudprovider
    namespace: shoot--foo--bar
  infrastructureProviderStatus:
    apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    ec2:
      keyName: shoot--foo--bar--bastion-ssh-publickey
    iam:
      instanceProfiles:
      - name: shoot--foo--bar--bastion-nodes
        purpose: nodes
      roles:
      - arn: arn:aws:iam::0123456789:role/shoot--foo--bar--bastion-nodes
        purpose: nodes
    vpc:
      id: vpc-0123456789
      securityGroups:
      - id: sg-123456789022 
        purpose: nodes
      subnets:
      - id: subnet-01234
        purpose: nodes
        zone: eu-west-1b
  pools:
  - name: cpu-worker
    minimum: 1
    maximum: 1
    maxSurge: 1
    maxUnavailable: 0
    machineType: t2.namo
    machineImage:
      name: coreos
      version: 1967.5.0
    userData: c29tZSBkYXRhIHRvIGJvb3RzdHJhcCB0aGUgVk0K
    volume:
      size: 20Gi
      type: gp2
    zones:
    - eu-west-1b
```


`MachineDeployment`

```
---
apiVersion: v1
kind: Secret
metadata:
  name: shoot--foo--bar-cpu-worker-z1-3db65
  namespace: shoot--foo--bar
  labels:
    garden.sapcloud.io/purpose: machineclass
type: Opaque
data:
  providerAccessKeyId: eW91ci1hd3MtYWNjZXNzLWtleS1pZAo=
  providerSecretAccessKey: eW91ci1hd3Mtc2VjcmV0LWFjY2Vzcy1rZXkK
  userData: c29tZSBkYXRhIHRvIGJvb3RzdHJhcCB0aGUgVk0K
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: AWSMachineClass
metadata:
  name: shoot--foo--bar-cpu-worker-z1-3db65
  namespace: shoot--foo--bar
spec:
  ami: ami-0123456789 # Your controller must map the stated version to the provider specific machine image information, in the AWS case the AMI.
  blockDevices:
  - ebs:
      volumeSize: 20
      volumeType: gp2
  iam:
    name: shoot--foo--bar-nodes
  keyName: shoot--foo--bar-ssh-publickey
  machineType: m4.large
  networkInterfaces:
  - securityGroupIDs:
    - sg-1234567890
    subnetID: subnet-01234
  region: eu-west-1
  secretRef:
    name: shoot--foo--bar-cpu-worker-z1-3db65
    namespace: shoot--foo--bar
  tags:
    kubernetes.io/cluster/shoot--foo--bar: "1"
    kubernetes.io/role/node: "1"
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineDeployment
metadata:
  name: shoot--foo--bar-cpu-worker-bastion-z1
  namespace: shoot--foo--bar
spec:
  replicas: 2
  selector:
    matchLabels:
      name: shoot--foo--bar-cpu-worker-bastion-z1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: shoot--foo--bar-cpu-worker-bastion-z1
    spec:
      class:
        kind: AWSMachineClass
        name: shoot--foo--bar-cpu-worker-bastion-z1-3db65
```
