### ISSUE TITLE
Support Access Restrictions

### ISSUE THREAD

**Issue by petersutter** [gardener/gardenctl#232]
**What would you like to be added**:
`Gardenctl` should add support for access restrictions. 
In case a shoot is flagged with an access restriction, `gardenctl` should notify /warn the operator before an operator accesses or starts with the troubleshooting and should inform about the access restriction. 

**How it could be configured in gardenctl**
A simplified version of the dashboard configuration for `gardenctl` could look like the following (which would need to be set for a garden configuration). This is just a proposal.
```yaml
gardenClusters:
- name: dev-virtual
  kubeConfig: path/to/kubeconfig
  accessRestrictions:
  - key: seed.gardener.cloud/eu-access
    notifyIf: true # this property is named visibleIf in the dashboard configuration
    title: EU Access # or combine title and description to `message`
    description: Do not migrate the cluster to a data center outside the EEA or Switzerland without the customer's prior written consent (email permitted). The service is offered with the regular SLAs and 24x7 support for the control plane of the cluster. 24x7 support for cluster add-ons and nodes is only available if the user complies to the conditions
    options:
    - key: support.gardener.cloud/eu-access-for-cluster-addons
      notifyIf: false
      title: EU Access Only for Cluster Addons Support # or combine title and description to `message`
      description: Do not access cluster add-ons such as DNS and certificates, Calico overlay network and network policies, kube-proxy and services, and everything else that would require direct inspection of the cluster through its API server in case you are not located in EEA. Only third-level/dev support at usual 8x5 working hours in EEA does apply in this case
    - key: support.gardener.cloud/eu-access-for-cluster-nodes
      notifyIf: false
      title: EU Access Only for Worker Node Support # or combine title and description to `message`
      description: Do not access all node-related components such as Docker and Kubelet, the operating system, and everything else that would require direct inspection of the nodes through a privileged pod or SSH in case you are not located in EEA. Only third-level/dev support at usual 8x5 working hours in EEA does apply in this case
```

**Notification to the operator**
With the above configuration, when e.g. targeting the following shoot
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  annotations:
    support.gardener.cloud/eu-access-for-cluster-addons: "true"
    support.gardener.cloud/eu-access-for-cluster-nodes: "false"
  ...
spec:
  seedSelector:
    matchLabels:
      seed.gardener.cloud/eu-access: "true"
```
The follwoing notification from `gardenctl` should be shown (as defined in the `gardenctl` configuration)

---
Please Note: The following access restrictions apply for shoot _${project}/${name}_:
- **EU Access**: Do not migrate the cluster to a data center outside the EEA or Switzerland without the customer's prior written consent (email permitted). The service is offered with the regular SLAs and 24x7 support for the control plane of the cluster. 24x7 support for cluster add-ons and nodes is only available if the user complies to the conditions
  - **EU Access Only for Worker Node Support**: Do not access all node-related components such as Docker and Kubelet, the operating system, and everything else that would require direct inspection of the nodes through a privileged pod or SSH in case you are not located in EEA. Only third-level/dev support at usual 8x5 working hours in EEA does apply in this case
---

**Additional Info**:
Corresponing PR in Dashboard: https://github.com/gardener/dashboard/pull/694
Corresponing PR in Gardener: https://github.com/gardener/gardener/pull/2340

See the description of gardener/dashboard#694 for an example configuration of the dashboard.

**Why is this needed**:
An operator should be notified in case a shoot shoot is flagged with an access restriction

**Comment by neo-liang-sap** [comment]
Hi @petersutter ,

Thanks for submitting this, here's some of my implementation proposal:

1) My suggestion is that, i can directly check shoot configuration:

say after https://github.com/gardener/gardenctl/blob/master/pkg/cmd/target.go#L1008

i can get shoot annotations via `shoots[0].GetAnnotations()`, i can get shoot labels via `shoots[0].GetLabels()`

a) if `shoot annotation` contains `support.gardener.cloud/eu-access-for-cluster-addons: "true"`, then i will display warning message like 

```
title: EU Access Only for Cluster Addons Support # or combine title and description to `message`
description: Do not access cluster add-ons such as DNS and certificates, Calico overlay network and network policies, kube-proxy and services, and everything else that would require direct inspection of the cluster through its API server in case you are not located in EEA. Only third-level/dev support at usual 8x5 working hours in EEA does apply in this case
```

b) if `shoot annotation` contains `support.gardener.cloud/eu-access-for-cluster-nodes: "true"`, then i will display warning msg like 

```
title: EU Access Only for Worker Node Support # or combine title and description to `message`
description: Do not access all node-related components such as Docker and Kubelet, the operating system, and everything else that would require direct inspection of the nodes through a privileged pod or SSH in case you are not located in EEA. Only third-level/dev support at usual 8x5 working hours in EEA does apply in this case
```

c) if `shoot labels` contains `seed.gardener.cloud/eu-access: "true"`, then i will display warning msg like
```
title: EU Access # or combine title and description to `message`
description: Do not migrate the cluster to a data center outside the EEA or Switzerland without the customer's prior written consent (email permitted). The service is offered with the regular SLAs and 24x7 support for the control plane of the cluster. 24x7 support for cluster add-ons and nodes is only available if the user complies to the conditions
```

Surely i will re-format the msg to make an better looking in terminal



2) if all gardens need to display warning msg for eu-access related shoots, i think 1) is enough, if say we have an testing environment which contains eu clusters but we don't want to display warning msgs, i can modify garden config like

```
gardenClusters:
- name: dev-virtual
  kubeConfig: path/to/kubeconfig
  accessRestrictions: true
```

if `accessRestrictions` is true, then logic in 1) will be performed, if `accessRestrictions` is false, then logic in 1) will be dismissed.


What do you think?
