### ISSUE TITLE
bug target --server

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#279]
**Describe the bug**
```
cat ~/.garden/config
gardenClusters:
- name: dev-gke
  kubeConfig: /Users/i333878/gardener_kubeconfig/dev/garden-gke/gke/kubeconfig
....
- name: canary-gke
  kubeConfig: /Users/i333878/gardener_kubeconfig/canary/garden-gke/gke/kubeconfig
- name: canary-virtual
  kubeConfig: /Users/i333878/gardener_kubeconfig/canary/garden-gke/kubeconfig
...
- name: ttt
  kubeConfig: /Users/i333878/gardener_kubeconfig/ttt/kubeconfig

```
```
gg target -g canary-virtual -t anxxxy14b8
Garden:
KUBECONFIG=/Users/i333878/gardener_kubeconfig/canary/garden-gke/kubeconfig
Shoot:
KUBECONFIG=/Users/i333878/.garden/cache/canary-virtual/projects/i333878/anxxxy14b8/kubeconfig.yaml
```

not sure whether a bug if I add new kubeconfig under config, then always pick up my kubeocnfig instead of canary-virtual 
```
 g target --server https://gardener.garden.canary.xxx --seed aws-eu3 --namespace shoot--i333878--fywubia85d
Garden:
KUBECONFIG=/Users/i333878/gardener_kubeconfig/ttt/kubeconfig
```

**To Reproduce**
to reproduce target any other garden first. then use `--server`  

**Expected behavior**

**Screenshots**

**Gardenctl Version (please complete the following information):**
 - Version/Commit [latest version]

**Additional context**
