### ISSUE TITLE
`gardenctl download tf infra` reports error when current stack is garden+seed+namespace

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#289]
**Describe the bug**
say we have current target stack:
```
~/git_repo/gardenctl(fix-download-error*) » gardenctl get target                                                           (ccee-m3/default)
target:
- kind: garden
  name: xxx
- kind: seed
  name: xxxx
- kind: namespace
  name: xxxxxxx
```
the command `gardenctl download tf infra` will report following error:

```
~/git_repo/gardenctl(add-test-cases*) » gardenctl download tf infra                                                        (ccee-m3/default)
Kubeconfig under path /Users/i352986/.garden/cache/live/seeds/az-eu2/kubeconfig.yaml contains exec configurations that could contain malicious code. Please only continue if you have verified it to be uncritical
Kubeconfig under path /Users/i352986/.garden/cache/live/seeds/az-eu2/kubeconfig.yaml contains exec configurations that could contain malicious code. Please only continue if you have verified it to be uncritical
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1fe837e]

goroutine 1 [running]:
github.com/gardener/gardenctl/pkg/cmd.downloadTerraformFiles(0x7ffeefbfed76, 0x5, 0xc00041fcf0, 0x114f6a4)
	/Users/i352986/git_repo/gardenctl/pkg/cmd/download.go:95 +0x5ae
github.com/gardener/gardenctl/pkg/cmd.NewDownloadCmd.func1(0xc0003ff340, 0xc0002d9380, 0x2, 0x2)
	/Users/i352986/git_repo/gardenctl/pkg/cmd/download.go:44 +0xed
github.com/spf13/cobra.(*Command).execute(0xc0003ff340, 0xc0002d92e0, 0x2, 0x2, 0xc0003ff340, 0xc0002d92e0)
	/Users/i352986/git_repo/gardenctl/vendor/github.com/spf13/cobra/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x30a3500, 0x1d, 0xc0001a3b40, 0x36)
	/Users/i352986/git_repo/gardenctl/vendor/github.com/spf13/cobra/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/i352986/git_repo/gardenctl/vendor/github.com/spf13/cobra/command.go:885
github.com/gardener/gardenctl/pkg/cmd.Execute()
	/Users/i352986/git_repo/gardenctl/pkg/cmd/root.go:112 +0x3aa
main.main()
	/Users/i352986/git_repo/gardenctl/cmd/gardenctl/main.go:20 +0x20
```

**To Reproduce**
1. Which target was set 'gardenctl get target'
```
target:
- kind: garden
  name: xxx
- kind: seed
  name: xxxx
- kind: namespace
  name: xxxxxxx
```
2. Which command was entered [e.g. 'gardenctl show vpn-seed']
`gardenctl download tf infra`
3. What was the output of the command 
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1fe837e]`
**Expected behavior**
this command should report "no shoots targeted"

**Screenshots**
![image](https://user-images.githubusercontent.com/42594392/91784231-f6207c00-ec34-11ea-997d-1e9dfbdda15e.png)

**Gardenctl Version (please complete the following information):**
 - Version/Commit [c62e0be1]

**Additional context**
