### ISSUE TITLE
gardenctl ssh returns `Error parsing parameter '--filters': Expected: '=', received: 'EOF' for input:` for AWS shoot cluster

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#322]
**Describe the bug**
say we have a sample AWS cluster
use gardenctl ssh to one of the node
![image](https://user-images.githubusercontent.com/42594392/93851391-9c1a5000-fce2-11ea-8615-ad2fea5fd6cc.png)

**To Reproduce**
1. Which target was set 'gardenctl get target'
```
 gardenctl get target                                                  
target:
- kind: garden
  name: xxxxxdev
- kind: project
  name: sretestneo
- kind: shoot
  name: neo-test-ar
```
2. Which command was entered [e.g. 'gardenctl show vpn-seed']
`gardenctl ssh ip-10-250-27-0.eu-west-1.compute.internal`
3. What was the output of the command 
```
Error parsing parameter '--filters': Expected: '=', received: 'EOF' for input:
under
     ^
```
**Expected behavior**
gardenctl ssh should success

**Screenshots**
see above
**Gardenctl Version (please complete the following information):**
 - Version/Commit [e.g. 8cc4e0c3]
```
gardenctl version                                                     (ccee-m3/default)
gardenctl:
		version     : v0.22.0
		build date  : 2020-09-21
		go version  : go1.14.6
		go compiler : gc
		platform    : darwin/amd64
```

**Additional context**

i'm not sure but i suspect this is due to recent changes in `ssh_aws.go`
![image](https://user-images.githubusercontent.com/42594392/93851591-fe735080-fce2-11ea-9786-b2ccd01cb64b.png)
