### ISSUE TITLE
some `gardenctl logs xxx` commands failed in oidc env due to missing permissions

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#426]
**Describe the bug**
In OIDC enabled env, `gardenctl logs` command failed at (at least, not fully verified for other commands) follow three parameter

`gardenctl logs gardener-apiserver`
`gardenctl logs gardener-controller-manager`
`gardenctl logs gardener-dashboard`

**To Reproduce**
1. Which target was set 'gardenctl get target'
```
gardenctl get target                                                                                   
target:
- kind: garden
  name: dev
- kind: project
  name: sretestneo
- kind: shoot
  name: neo-test-ar
```
2. Which command was entered [e.g. 'gardenctl show vpn-seed']
`gardenctl logs gardener-apiserver`
`gardenctl logs gardener-controller-manager`
`gardenctl logs gardener-dashboard`
3. What was the output of the command 
`pods is forbidden: User "neo.liang@sap.com" cannot list resource "pods" in API group "" in the namespace "garden"`

**Expected behavior**
the logs should be displayed without error
**Screenshots**
![image](https://user-images.githubusercontent.com/42594392/98188208-8e94ee80-1f4d-11eb-98ba-2cc47d5df1e5.png)

**Gardenctl Version (please complete the following information):**
 latest version on master branch

**Additional context**
