### ISSUE TITLE
validateArgs bug in "gardenctl logs tf"

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#470]
**Describe the bug**

Say we have current target stack:
```
gardenctl get target                       (ccee-m3/default)
target:
- kind: garden
  name: dev
- kind: seed
  name: aws
- kind: namespace
  name: shoot--sretestneo--neo-test-ar
```
we have a seed targeted

But in logic https://github.com/gardener/gardenctl/commit/16fc236f9ff027a465d4075eccb2c5c9dd9f9d21#diff-59f23253994b1605ea49a120ea68de0c2ee3a4240c2825bb741f7b707695211fR80 , gardenctl will fall into `return errors.New("No seed or shoot targeted")`

this commit is included in https://github.com/gardener/gardenctl/pull/404 - @tedteng  could you please check it when you have time? thanks!

**To Reproduce**
1. target the stack as above
2. run gardenctl logs tf 

**Expected behavior**
As seed is already targeted, gardenctl logs tf should run success

**Screenshots**
![image](https://user-images.githubusercontent.com/42594392/100317268-0a3b0600-2ff7-11eb-9c1b-ddc357b82963.png)

**Gardenctl Version (please complete the following information):**
latest in master branch

**Additional context**
