### ISSUE TITLE
What does a garden config look like

### ISSUE THREAD

**Issue by dfishburn** [gardener/gardenctl#505]
**Describe the bug**
I am finding difficulty configuring gardenctl for the features indicated.
I cannot find documentation which directly lists all the things than can / should go into the garden.config file.

**To Reproduce**

Version:
```
$ gardenctl version
gardenctl:
                version     : v0.24.1
                build date  : 2020-12-09
                go version  : go1.14.12
                go compiler : gc
                platform    : linux/amd64
```
I used this configuration:
```
email: blah@blah.com
githubURL: https://github.my.company
gardenClusters:
- name: devaws
  kubeConfig: ~/.kube/iotdevk8s--devawsk8s-cluster-admin.yaml
  dashboardUrl: http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/
  # No idea what any of this does
  # accessRestrictions:
  # - key: aws.eu6
  # - key: seed.gardener.cloud/eu-access
  #   notifyIf: true 
  #   msg: warning msg
  #   options:
  #   - key: support.gardener.cloud/eu-access-for-cluster-addons
  #     notifyIf: true
  #     msg: warning msg
  #   - key: support.gardener.cloud/eu-access-for-cluster-nodes
  #     notifyIf: true
  #     msg: warning msg
- name: prod
  kubeConfig: ~/clusters/prod/kubeconfig.yaml
```
**Expected behavior**
```
$ gardenctl ls
Error: command must be in the format: ls [gardens|projects|seeds|shoots|issues|namespaces]
```
Trying each of these commands:
```
$ gardenctl get target
target:
- kind: garden
  name: devaws
```
That worked as I set the target earlier.
```
$ gardenctl ls gardens
gardenClusters:
- name: devaws
- name: prod
```
I can see those came from my garden.conf file.

Now the remainder of the commands simply fail.
  - No idea what changes I need to make them work.
``` 
$ gardenctl ls projects
Error: the server could not find the requested resource (get projects.core.gardener.cloud)

$ gardenctl ls seeds
2021/03/01 15:56:33 the server could not find the requested resource (get seeds.core.gardener.cloud)

$ gardenctl ls shoots
Error: the server could not find the requested resource (get projects.core.gardener.cloud)
```
Namespaces work, as I already had a target.
```
$ gardenctl ls namespaces
NAME                       STATUS   AGE
broker                     Active   3d2h
default                    Active   3d3h
```

What I am trying to do (connected to AWS) is:
  - Choose a project inside Gardener
  - Connect to a cluster
    - If possible, find the VpcId of the worker node
  - List all the shoots created
    - Find the first once
    - Using the AWS Cli, look up the InstanceId, and the VpcId it is attached to

Just can't figure out how to get it to return the data I am interested in.
