### ISSUE TITLE
gardenctl v2 - SSH controller proposal - old

### ISSUE THREAD

**Issue by petersutter** [gardener/gardenctl#508]
## Motivation
`gardenctl` (v1) has the functionality to setup ssh sessions to the targeted shoot cluster. For this, infrastructure resources like vms, firewall rules etc have to be created. `gardenctl` will clean up the resources after the SSH session. However there were issues in the past where that infrastructure resources did not get cleaned up properly, e.g. due to some error and was not retried. Hence the proposal, to have a dedicated controller (for each infrastructure) that manages the infrastructure resources. `gardenctl` also re-used the ssh node credentials which were used by each user. Instead, ssh credentials should be created for each user / ssh session.
> This way, operators would have auditable and personalised ssh credentials that last only for a given time.
https://github.com/gardener/gardenctl/issues/499#issue-771305172

## Assumption
The ssh controller on the seed has access to the garden cluster and is allowed to read/watch `SSH` resources created by the user

## New Components involved in SSH Flow (naming to be defined)
- `gardenctlv2`
- Provider specific SSH Controller
  - Runs on seed
  - Should be added to gardener-extension-provider-<infra> repos, e.g. https://github.com/gardener/gardener-extension-provider-aws/tree/master/pkg/controller
  - types: optional `SSHConfig`: contains provider-specific configuration that is embedded into `SSH` resource
- Central SSH Controller
  - Runs on garden runtime cluster
  - Defines types (e.g. `SSH` resource)
  - Heartbeat controller
  - Runs Admission Webhook server

## SSH Flow
1. User/`gardenctlv2` creates `SSH` Resource in garden cluster (see resource example below)
2. Mutating Webhook (Central SSH Controller) for the `SSH` resource
  - according to shootRef, sets the `spec.seedName`
  - according to shootRef, sets the `spec.providerType`
3. ~~Validating Webhook (Central SSH Controller) ensures~~
  - ~~that there is a validating webhook configuration for the `SSH` resource~~
  - ~~that the user has certain role in the project where the referenced cluster is (or has the permission to read the secret)? What about garden namespace not having a corresponding project? See question (6) at the bottom~~
  - ~~the `SSH` resource was created AFTER the validating webhook configuration was created~~
4. SSH Controller on Seed:
  - Watches `SSH` resources for own seed
  - Create User's node credentials (public key authentication)
  - Node fetches these credentials and updates sshd configuration
  - Controller reads `cloudprovider` credentials from seed-shoot namespace
  - Deploy infrastructure resources
    - bastion host vm, should instrument the machine controller manager if possible
    - create security groups / firewall rules etc  using the respective infrastructure SDKs.
  - Write SSH keypair to garden cluster as secret (to be discussed)
  - Updates status of SSH resource with bastionNode, sshKeypair secret reference. Sets ready flag on resource so that the client knows when to initiate the SSH connection
5. gardenctl
  - reads secret of sshKeypair and initiates SSH session
  - runs heartbeat in parallel as long as the SSH session is open
6. After missing heartbeat (configurable) a heartbeat controller, running on the garden runtime cluster, will delete the `SSH` resource
7. Once the `SSH` resource gets deleted, all created resources should be cleaned up by the provider specific ssh controller

**Example**
```yaml
apiVersion: operations.gardener.cloud/v1alpha1
kind: SSH
metadata:
  generateName: cli-
  namespace: garden-myproject
  annotations:
    operations.gardener.cloud/created-by: foo # set by the mutating webhook
    operations.gardener.cloud/last-heartbeat-at: "2021-03-19T11:58:00Z"
    # operations.gardener.cloud/operation: keepalive # this annotation is removed by the mutating webhook and the last-heartbeat-at timestamp will be updated
spec:
  shootRef: # namespace cannot be set / it's the same as .metadata.namespace
    name: my-cluster

  # seedName: aws-eu2 # is set by the mutating webhook
  # providerType: aws # is set by the mutating webhook

  clientIP: # external ip of the user
    ipv4: 1.2.3.4
    # ipv6: ::1

  # sshConfig: # optional
  #   apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
  #   kind: SSHConfig
  #   foo: bar

  # lifetime: 30m # alternative to the last-heartbeat-at timestamp in the anntoations. Only one approach should be chosen

status:
  bastionNode: 1.2.3.5 # or with user, like foo@1.2.3.5, or have own field for the user, or should the user information be stored in own (secret) resource?
  sshKeypair: # secret reference
    name: foo
    namespace: bar
```

## Open questions
1. How to handle seed migrations of a shoot? Central SSH Controller deletes `SSH` resource?
  - Proposal: forbid the migration when SSH resources still exist
2. Should the user be allowed to set the `spec.seedName` in the `SSH` resource?
  - Answer: Mutating webhook will ensure that the correct seedName is set
3. Is there a better way to "hand out" the user's node credentials to the user (spec.sshKeypair), without storing it as secret in the garden cluster in the respective project namespace?
  - Answer: Sounds reasonable
4. Garden cluster access of ssh controller:
      a) "static" kubeconfig is set in controller registions' `providerConfig.values` https://github.com/gardener/gardener/blob/master/docs/extensions/controllerregistration.md#scenario-1-deployed-by-gardener.
      b) Sync with @mvladev regarding the concept of authentication between clusters without static credentials
5. Having `spec.clientIP` in the `SSH` resources exposes the external ip of the user to an attacker that has access to the garden cluster with read permission for the `SSH` resources
6.  ~~How to ensure that the user is allowed to create an ssh session for the respective shoot? With the `terminal-controller-manager`, the approach is to check, if the user has the permission to read the referenced kubeconfig secret. If allowed, the `Terminal` resource is created and the controller acts upon it. The proposal above was to check if the user has a certain role in the project, however operators currently have no role in a user's project. So there must be other means to check this. Ideas?~~
