### ISSUE TITLE
Design Proposal for uniform Garden Cluster access

### ISSUE THREAD

**Issue by DockToFuture** [gardener/gardenctl#54]
The garden cluster setup has changed over time and is most likely setup in one of the following three ways shown in the proposal. To unify access over ```gardenctl``` it is proposed to store the credentials for the garden cluster in separate secrets (as shown in SampleSecret) in the ```garden``` namespace of the virtual cluster. The secret should be annotated with a garden specific key to be able to be parsed by ```gardenctl```.  And can than be accessed in an uniform way, which is illustrated as the black arrows.

![gardensetupforcli-1](https://user-images.githubusercontent.com/30324854/51040344-85d46b00-15b7-11e9-8652-4445e4642b61.png)

Sample Secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: garden-secret
  namespace: garden
  labels:
      runtime: garden
  annotations:
    clusterName: garden-dev
type: Opaque
data:
  kubeconfig: b64(kubeconfig-to-cluster)
```
